version: 2
jobs:
  build:
    docker:
    - image: circleci/node:10.15
    steps:
    - checkout
    - run:
        command: |
          echo 'export VERSION=$(npm run version)' >> $BASH_ENV
          source $BASH_ENV
workflows:
  version: 2
  workflow:
    jobs:
      - build:
          # triggers:
          #   - push
          #   - delete
          filters:
            tags:
              only: /^[v]\d+\.\d+\.\d+$/
            branches:
              ignore: /.*/

# version: 2.1
# executors:
#   tester:
#     docker:
#       - image: circleci/node:10.15
# jobs:
#   build:
#     executor: tester
#     steps:
#       - checkout
#       - run: echo "henlo"