version: 2.1
executors:
  node:
    docker:
      - image: circleci/node:10.15
jobs:
  build-production:
    executor: node
    steps:
      - checkout
      - run:
          name: Building Production
          command: echo 'running the production build'
  build-staging:
    executor: node
    steps:
      - checkout
      - run:
          name: Building Staging
          command: echo 'running the staging build'

workflows:
  version: 2.1
  workflow:
    jobs:
      - build-production:
          filters:
            tags:
              only: /^[v]\d+\.\d+\.\d+$/
            branches:
              ignore: /.*/
      - build-staging:
          filters:
            tags:
              only: ^[v]\d+\.\d+\.\d+\-\b(alpha|beta|rc)(.[\d]+)?$
            branches:
              ignore: /.*/