version: 2.1
executors:
  node:
    docker:
      - image: circleci/node:10.15
jobs:
  build-prod:
    executor: node
    steps:
      - checkout
      - run:
          name: Building Production
          command: echo 'running the build'
workflows:
  version: 2.1
  workflow:
    jobs:
      - build-prod:
          filters:
            tags:
              only: /^[v]\d+\.\d+\.\d+$/
            branches:
              ignore: /.*/